apiVersion: v1
kind: Service
metadata:
  name: booking-app-backend-loadbalancer
  labels:
    app: booking-app-backend
  namespace: applications
spec:
  type: LoadBalancer
  selector:
    app: booking-app-backend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080